// TIMBER-2 — coverings: "beyond framing" (plan §2.6, C-5/C-9).
//
// Everything that closes a building in — wall sheathing, siding, roof deck, felt, roll and
// corrugated roofing — is generated by tiling a PLANE, and every plane comes from a contract
// somebody else owns (`wallSystem.surfaces`, `roofFamilies.roofPlanes`). Nothing here
// re-derives where a wall or a slope is.
//
// C-5, the conservation rule, is the test that makes this trustworthy: covered area + cutout
// area must equal the surface area to 1e-6 sf wherever the cutouts come from the same
// coordinates as the panels. A siding job that silently loses two square feet is a siding job
// that arrives two sheets short.
//
// C-9: the legacy stage-9 roof deck is NOT generated here. That course loop is byte-pinned by
// the compat goldens and stays in the frozen `roof.ts`. This module's generalized tiler serves
// new roof kinds and any surface with cutouts.

import type { Member } from '../types';
import { DRESSED } from '../types';
import { makeEmitter } from '../emit';
import { PANEL, ROOFING, SIDING, LUMBER, TOLERANCE, IN_PER_FT, citeOf } from '../doctrine';
import { planeSpanAt, type RoofPlane } from './roofFamilies';
import type { WallSurface } from './wallSystem';

/** A rectangle in a surface's own (u, v) coordinates. */
export interface Rect { u0: number; u1: number; v0: number; v1: number }

/** One tile the layout produced, still in surface coordinates. */
export interface Tile extends Rect {
  /** Full-size tiles are whole sheets; the rest are cut on site. */
  full: boolean;
}

const EPS = 1e-9;
const area = (r: Rect): number => Math.max(0, r.u1 - r.u0) * Math.max(0, r.v1 - r.v0);

/**
 * Subtract cutouts from a tile, splitting it into at most four sub-rects (left / right /
 * below / above). Panels around a window are cut, not omitted — the sheet is still bought.
 */
export function subtractCutouts(tile: Rect, cutouts: Rect[]): Rect[] {
  let pieces: Rect[] = [tile];
  for (const c of cutouts) {
    const next: Rect[] = [];
    for (const p of pieces) {
      const overlapU0 = Math.max(p.u0, c.u0);
      const overlapU1 = Math.min(p.u1, c.u1);
      const overlapV0 = Math.max(p.v0, c.v0);
      const overlapV1 = Math.min(p.v1, c.v1);
      if (overlapU1 - overlapU0 <= EPS || overlapV1 - overlapV0 <= EPS) {
        next.push(p); // no overlap
        continue;
      }
      if (p.u0 < overlapU0 - EPS) next.push({ ...p, u1: overlapU0 });
      if (overlapU1 < p.u1 - EPS) next.push({ ...p, u0: overlapU1 });
      if (p.v0 < overlapV0 - EPS) next.push({ u0: overlapU0, u1: overlapU1, v0: p.v0, v1: overlapV0 });
      if (overlapV1 < p.v1 - EPS) next.push({ u0: overlapU0, u1: overlapU1, v0: overlapV1, v1: p.v1 });
    }
    pieces = next;
  }
  return pieces.filter((p) => area(p) > EPS);
}

/**
 * Lay sheet goods over a surface: full sheets from the origin, courses offset by `stagger`,
 * last row and column cut to fit — never overlapped, which would double-count material.
 *
 * `span` clips each course to the surface's own width at that height. A rectangle passes the
 * full run at every height and comes out exactly as before; a hip's trapezoid narrows toward
 * the ridge and its ends narrow to a point. The clip is per COURSE rather than per tile
 * because that is how the material is cut on site — you snap a line and cut the row.
 *
 * WHERE a tapered course is clipped is the whole problem, because a rectangle cannot be cut on
 * a diagonal and every choice leaves an artifact somewhere:
 *
 *   'cover' takes the course's WIDEST edge. Nothing is left bare, and the pieces overhang the
 *     hip by up to half a course into the neighbouring slope's airspace.
 *   'average' takes the MID-height width. Exact area — the taper is linear, so mid-height is
 *     the course's true average — and nothing overhangs, at the cost of thin triangular gaps
 *     hugging the hip lines.
 *
 * Both are used, one per layer, and the pairing is what makes a hip look right:
 * the DECK averages (its gaps sit under the roofing, unseen, and its diagonal offcuts are
 * genuinely reusable because a hip's four corners are mirror pairs — the triangle cut off at
 * one is the piece needed at another), and the ROOFING covers (it is the visible surface, so
 * it must be complete, and a small overlap along the hip reads as the hip cap it would have).
 *
 * Getting this backwards is what the first two attempts did, and both looked plausible in a
 * summary: averaging BOTH layers put diamond-shaped holes along every hip with framing showing
 * through, and covering both floated tan deck panels above the neighbouring roofing.
 */
export type TaperClip = 'cover' | 'average';

export function tileSurface(
  runFt: number,
  heightFt: number,
  sheetWFt: number,
  sheetHFt: number,
  stagger = 0,
  span?: (v: number) => { lo: number; hi: number },
  clip: TaperClip = 'cover',
): Tile[] {
  const tiles: Tile[] = [];
  let row = 0;
  for (let v = 0; v < heightFt - EPS; v += sheetHFt, row++) {
    const v1 = Math.min(v + sheetHFt, heightFt);
    const edges = span
      ? (clip === 'average' ? [span((v + v1) / 2)] : [span(v), span(v1)])
      : [{ lo: 0, hi: runFt }];
    const lo = Math.min(...edges.map((e) => e.lo));
    const hi = Math.max(...edges.map((e) => e.hi));
    if (hi - lo <= EPS) continue; // the point at the top of a hip end — nothing to cut
    const off = row % 2 === 1 ? stagger : 0;
    let u = lo;
    if (off > 0) {
      const first = Math.min(lo + off, hi);
      tiles.push({ u0: lo, u1: first, v0: v, v1, full: false });
      u = first;
    }
    for (; u < hi - EPS; u += sheetWFt) {
      const u1 = Math.min(u + sheetWFt, hi);
      tiles.push({ u0: u, u1, v0: v, v1, full: u1 - u >= sheetWFt - EPS && v1 - v >= sheetHFt - EPS });
    }
  }
  return tiles;
}

// ── Wall surfaces ────────────────────────────────────────────────────────────

export interface WallCoveringInput {
  surfaces: WallSurface[];
  kind: 'plywood' | 'boards' | 'boardAndBatten';
  role: 'sheathingPanel' | 'siding';
  stage: number;
  /** Outward offset from the wall face — sheathing sits on it, siding sits on the sheathing. */
  standoffFt: number;
}

/** Place a tile on a wall surface, returning world position + rotation. */
function wallTilePlacement(
  s: WallSurface,
  t: Rect,
  standoffFt: number,
  thickFt: number,
): { position: [number, number, number]; rotation: [number, number, number]; widthFt: number; heightFt: number } {
  const uMid = (t.u0 + t.u1) / 2;
  const vMid = (t.v0 + t.v1) / 2;
  const out = s.faceOffsetFt + standoffFt + thickFt / 2;
  const x = s.origin[0] + s.along[0] * uMid + s.normal[0] * out;
  const z = s.origin[1] + s.along[1] * uMid + s.normal[1] * out;
  const yaw = Math.atan2(-s.along[1], s.along[0]);
  return {
    position: [x, vMid, z],
    // Panel convention (matches the frozen subfloor/roof panels): length along local X, face
    // width along local Y, thickness along local Z — so a vertical wall panel is the plane
    // rotated to stand up.
    rotation: [0, yaw, 0],
    widthFt: t.u1 - t.u0,
    heightFt: t.v1 - t.v0,
  };
}

export function generateWallCovering(input: WallCoveringInput): Member[] {
  const emit = makeEmitter('CV');
  const { surfaces, kind, role, stage, standoffFt } = input;

  for (const s of surfaces) {
    const cutouts: Rect[] = s.cutouts.map((c) => ({ u0: c.u0, u1: c.u1, v0: c.v0, v1: c.v1 }));

    if (kind === 'plywood') {
      const thick = (PANEL.sidingThickIn.value as number) / IN_PER_FT;
      const sheetW = PANEL.widthFt.value as number;
      const sheetH = PANEL.lengthFt.value as number;
      // Sheets stand on end (4 ft wide, 8 ft tall) so joints land on studs.
      for (const t of tileSurface(s.runFt, s.heightFt, sheetW, sheetH)) {
        for (const piece of subtractCutouts(t, cutouts)) {
          const p = wallTilePlacement(s, piece, standoffFt, thick);
          emit(role, `${PANEL.widthFt.value}x${PANEL.lengthFt.value} panel`, {
            cutLengthFt: p.widthFt,
            position: p.position,
            rotation: p.rotation,
            stage,
            wall: s.wall,
            actual: { w: PANEL.sidingThickIn.value as number, d: p.heightFt * IN_PER_FT },
            nailing: '8d @ 6" edges / 12" field (PH)',
            doctrineRef: `${citeOf(PANEL.sidingThickIn)} — joints on studs, cut around openings`,
          });
        }
      }
      continue;
    }

    // Board siding and board-and-batten: vertical boards run at their TRUE dressed width and
    // the last one is ripped to close the wall — which is what happens on site, and what keeps
    // the take-off honest. (Spacing boards at some computed cell width instead would bill each
    // one at its nominal face width while covering slightly less, and the C-5 conservation
    // check catches exactly that: a third of a square foot per wall, invisible by eye.)
    const boardNominal = SIDING.boardNominal.value as string;
    const boardW = DRESSED[boardNominal]!.d / IN_PER_FT;
    const boardT = DRESSED[boardNominal]!.w / IN_PER_FT;
    const seams: number[] = [];
    for (let u = 0; u < s.runFt - EPS; u += boardW) {
      const u1 = Math.min(u + boardW, s.runFt);
      if (u > 0) seams.push(u);
      const strip: Rect = { u0: u, u1, v0: 0, v1: s.heightFt };
      for (const piece of subtractCutouts(strip, cutouts)) {
        const p = wallTilePlacement(s, piece, standoffFt, boardT);
        emit(kind === 'boardAndBatten' ? 'sidingBoard' : role, boardNominal, {
          cutLengthFt: p.heightFt,
          position: p.position,
          rotation: [0, p.rotation[1], Math.PI / 2],
          stage,
          wall: s.wall,
          // The board's covered width — its dressed face, or the ripped remainder at the end.
          actual: { w: DRESSED[boardNominal]!.w, d: p.widthFt * IN_PER_FT },
          nailing: '8d @ 12" (PH)',
          doctrineRef: citeOf(SIDING.boardNominal),
        });
      }
    }
    if (kind === 'boardAndBatten') {
      const battenNominal = SIDING.battenNominal.value as string;
      const battenW = DRESSED[battenNominal]!.d / IN_PER_FT;
      const battenT = DRESSED[battenNominal]!.w / IN_PER_FT;
      for (const seam of seams) {
        const strip: Rect = { u0: seam - battenW / 2, u1: seam + battenW / 2, v0: 0, v1: s.heightFt };
        for (const piece of subtractCutouts(strip, cutouts)) {
          const p = wallTilePlacement(s, piece, standoffFt + boardT, battenT);
          emit('batten', battenNominal, {
            cutLengthFt: p.heightFt,
            position: p.position,
            rotation: [0, p.rotation[1], Math.PI / 2],
            stage,
            wall: s.wall,
            nailing: '8d @ 12" into the joint (PH)',
            doctrineRef: citeOf(SIDING.battenNominal),
          });
        }
      }
    }
  }
  return emit.members;
}

// ── Roof surfaces ────────────────────────────────────────────────────────────

function roofTilePlacement(
  p: RoofPlane,
  t: Rect,
  liftFt: number,
): { position: [number, number, number]; yaw: number; pitch: number } {
  const uMid = (t.u0 + t.u1) / 2;
  const vMid = (t.v0 + t.v1) / 2;
  const x = p.origin[0] + p.alongEave[0] * uMid + p.upSlope[0] * vMid + p.normal[0] * liftFt;
  const y = p.origin[1] + p.alongEave[1] * uMid + p.upSlope[1] * vMid + p.normal[1] * liftFt;
  const z = p.origin[2] + p.alongEave[2] * uMid + p.upSlope[2] * vMid + p.normal[2] * liftFt;
  const yaw = Math.atan2(-p.alongEave[2]!, p.alongEave[0]!);
  const pitch = Math.asin(Math.max(-1, Math.min(1, p.upSlope[1]!)));
  // Callers rotate a tile with [PI/2 - pitch, yaw, 0] in YXZ order, and the sign is NOT a free
  // choice: composing Ry(yaw)·Rx(rx) sends the tile's local +Y to (sin rx·sin yaw, cos rx,
  // sin rx·cos yaw), which equals this plane's upSlope only at rx = +(PI/2 - pitch). The far
  // slope of a gable comes out right by the same expression because its alongEave points -x, so
  // its yaw is already PI and the mirroring is in there. A `-Math.sign(upSlope.z)` factor used
  // to sit in front of it, correcting the far slope a SECOND time and tilting the near slope
  // backwards: its courses ran downhill under the deck, and the deck striped through between
  // them. Anything that lands on a roof plane rotates by this and nothing else.
  return { position: [x, y, z], yaw, pitch };
}

export interface RoofCoveringInput {
  planes: RoofPlane[];
  deck: 'none' | 'plywood' | 'boards' | 'skip' | 'purlins';
  roofing: 'none' | 'roll' | 'rollDouble' | 'corrugated';
  buildingPaper?: boolean;
  stageDeck: number;
  stageRoofing: number;
  /** Half the rafter depth — the deck sits on the rafter tops, not in them. */
  rafterHalfFt: number;
  /**
   * True when the deck named above is already on the roof because somebody else laid it — for a
   * gable, the frozen `roof.ts` course loop (C-9). This module then skips EMITTING it, so the
   * bill is not doubled, but its thickness still counts: roofing goes on top of a deck whoever
   * built it. Conflating "I am not placing this" with "this is not there" put the first roofing
   * course half an inch INTO the deck, and the deck showed through along both eaves.
   */
  deckLaidElsewhere?: boolean;
}

export function generateRoofCovering(input: RoofCoveringInput): Member[] {
  const emit = makeEmitter('CV');
  const { planes, deck, roofing, stageDeck, stageRoofing, rafterHalfFt, deckLaidElsewhere } = input;
  // What is UNDER the roofing, regardless of who put it there.
  const deckThick = deck === 'plywood' || deck === 'boards' ? (PANEL.roofDeckThickIn.value as number) / IN_PER_FT : 0;

  // ── Deck
  if (!deckLaidElsewhere && (deck === 'plywood' || deck === 'boards')) {
    const thick = (PANEL.roofDeckThickIn.value as number) / IN_PER_FT;
    const sheetW = PANEL.lengthFt.value as number; // 8 ft along the eave
    const sheetH = PANEL.widthFt.value as number; // 4 ft up the slope
    for (const plane of planes) {
      for (const t of tileSurface(plane.eaveLengthFt, plane.slopeLengthFt, sheetW, sheetH, 0,
        (v) => planeSpanAt(plane, v), 'average')) {
        const p = roofTilePlacement(plane, t, rafterHalfFt + thick / 2);
        emit('roofPanel', `${PANEL.widthFt.value}x${PANEL.lengthFt.value} panel`, {
          cutLengthFt: t.u1 - t.u0,
          position: p.position,
          rotation: [Math.PI / 2 - p.pitch, p.yaw, 0],
          stage: stageDeck,
          actual: { w: PANEL.roofDeckThickIn.value as number, d: (t.v1 - t.v0) * IN_PER_FT },
          nailing: '8d @ 6" edges / 12" field (PH)',
          doctrineRef: citeOf(PANEL.roofDeckThickIn),
        });
      }
    }
  }

  // ── Roofing: courses from the eave up, each lapping the one below.
  if (roofing !== 'none') {
    const isRoll = roofing === 'roll' || roofing === 'rollDouble';
    const widthIn = isRoll ? (ROOFING.rollWidthIn.value as number) : (ROOFING.corrugatedWidthIn.value as number);
    const lapIn = isRoll
      ? (roofing === 'rollDouble' ? widthIn / 2 : (ROOFING.rollEndLapIn.value as number))
      : (ROOFING.corrugatedSideLapIn.value as number);
    const exposureFt = (widthIn - lapIn) / IN_PER_FT;
    const courseWFt = widthIn / IN_PER_FT;
    const nominal = isRoll
      ? (roofing === 'rollDouble' ? 'roll roofing (double coverage)' : 'roll roofing')
      : `corrugated ${ROOFING.corrugatedWidthIn.value}x${ROOFING.corrugatedLengthFt.value}`;
    const cite = isRoll
      ? (roofing === 'rollDouble' ? citeOf(ROOFING.rollDoubleMinSlopePer12) : citeOf(ROOFING.rollMinSlopePer12))
      : citeOf(ROOFING.corrugatedWidthIn);

    for (const plane of planes) {
      const courses = Math.max(1, Math.ceil(plane.slopeLengthFt / exposureFt));
      for (let c = 0; c < courses; c++) {
        const v0 = c * exposureFt;
        // Cut the top course AT the ridge. The old `Math.max(slopeLength, v0 + exposure)` floor
        // meant the last course kept its full width no matter where the slope ended, so on a
        // 11.6-ft slope the fifth 3-ft course ran to 12.5 ft — nine inches of roofing standing
        // past the peak in mid-air, which is the stepped lip visible along the ridge. `courses`
        // is ceil(slopeLength / exposure), so every v0 is already short of the ridge and this
        // can never produce an empty course.
        const v1 = Math.min(v0 + courseWFt, plane.slopeLengthFt);
        // A hip's courses get SHORTER toward the ridge, and on its triangular ends they run
        // out to nothing. Roofing is the VISIBLE surface, so it takes the course's widest edge
        // and is complete: averaging it leaves stripes of bare deck along both hips. The small
        // overlap where it crosses a hip reads as the hip cap it would have on a real roof.
        const a = planeSpanAt(plane, v0);
        const b = planeSpanAt(plane, v1);
        const lo = Math.min(a.lo, b.lo);
        const hi = Math.max(a.hi, b.hi);
        const courseRun = hi - lo;
        if (courseRun <= TOLERANCE.epsFt) continue;
        const sheetLen = isRoll ? courseRun : (ROOFING.corrugatedLengthFt.value as number);
        const runs = isRoll ? 1 : Math.ceil(courseRun / sheetLen);
        for (let r = 0; r < runs; r++) {
          const u0 = lo + r * sheetLen;
          const u1 = Math.min(u0 + sheetLen, hi);
          // Each course laps the one below it, so consecutive courses share `lapIn` of the
          // slope. Placed at one common lift they were two slabs in the same plane —
          // interpenetrating, z-fighting, and reading as a stepped seam the width of the lap.
          // Stack them instead: course c rides on the c courses under it. The buildup is real
          // (lapped roofing does thicken toward the ridge) and tiny — five 1/4-in courses is
          // 1 1/4 in over a 12-ft slope — but it is what turns the lap into a clean shadow line.
          // `roofTilePlacement`'s lift is to the tile's CENTRE, so every term here is measured
          // to the middle of the course: rafter top, deck, a hair of clearance, the courses
          // already under this one, and finally half of this course's own thickness. Leaving
          // that last half out sank each course an eighth of an inch INTO the deck, and the
          // deck striped through — the same class of mistake as the sign above, seen twice.
          const coveringThick = (ROOFING.coveringThickIn.value as number) / IN_PER_FT;
          const p = roofTilePlacement(
            plane,
            { u0, u1, v0, v1 },
            rafterHalfFt + deckThick + TOLERANCE.surfaceLiftFt + c * coveringThick + coveringThick / 2,
          );
          emit('roofingCourse', nominal, {
            cutLengthFt: u1 - u0,
            position: p.position,
            rotation: [Math.PI / 2 - p.pitch, p.yaw, 0],
            stage: stageRoofing,
            actual: { w: ROOFING.coveringThickIn.value as number, d: (v1 - v0) * IN_PER_FT },
            nailing: isRoll ? 'roofing nails @ 6" laps (PH)' : 'lead-head nails at every 3rd corrugation (PH)',
            doctrineRef: cite,
          });
        }
      }
    }
  }

  return emit.members;
}

/** Skid runners under a building on grade (foundation 'skids'). */
export function generateSkids(lengthFt: number, widthFt: number, stage: number, count = 3): Member[] {
  const emit = makeEmitter('FL');
  const nominal = LUMBER.skidNominal.value as string;
  const d = DRESSED[nominal]!.d / IN_PER_FT;
  for (let i = 0; i < count; i++) {
    const z = (widthFt / (count - 1 || 1)) * i;
    emit('skid', nominal, {
      cutLengthFt: lengthFt,
      position: [lengthFt / 2, -d / 2, Math.min(Math.max(z, d / 2), widthFt - d / 2)],
      rotation: [0, 0, 0],
      stage,
      nailing: 'drift-pinned; chamfer both ends for dragging (PH)',
      doctrineRef: citeOf(LUMBER.skidNominal),
    });
  }
  return emit.members;
}
