// TIMBER-2 — the bearing-driven floor (plan C-10, §3.2.2).
//
// C-10 splits the floor in two on purpose. The LEGACY layout — rims at the building edge, one
// girder at mid-width, posts on pads — lives in the frozen `floor.ts` and is pinned byte for
// byte by the compat goldens. This is the SIBLING branch: it frames a deck over whatever
// bearing lines it is handed, which is what skids, a slab, a platform, and a second story all
// need. Neither branch can break the other, because neither calls the other.
//
// §3.2.2, the small-plan rule: below 8 ft of width there is NO girder line. Joists clear-span
// sill to sill, and on skids the skids themselves are the bearers. Without this the generator
// was degenerate on the catalog's own small plans — a 4x4 guard shack would get a girder
// 2 feet from each wall, which nobody has ever built.

import type { Member } from '../types';
import { DRESSED } from '../types';
import { makeEmitter } from '../emit';
import { LUMBER, LAYOUT, PANEL, TOLERANCE, IN_PER_FT, citeOf } from '../doctrine';
import { crossBridgingRise } from '../bridgingRise';
import type { BearingLine } from './wallSystem';

export interface FloorSystemInput {
  lengthFt: number;
  widthFt: number;
  joistSpacingIn: number;
  /** Top of the finished deck, feet. Everything below hangs from this. */
  deckTopY: number;
  /** Lines the joists bear on, running along X (perimeter and any interior girder). */
  bearings: BearingLine[];
  deck: 'panel' | 'plank' | 'none';
  stageFloor: number;
  stageDeck: number;
  prefix: string;
  /** Emit bridging rows when a span calls for them (off for shallow platforms). */
  bridging?: boolean;
}

/** Below this width the floor is girderless — joists clear-span (plan §3.2.2). */
export const SMALL_PLAN_WIDTH_FT = LAYOUT.smallPlanWidthFt.value as number;

/** The joist size a span calls for. 2x6 clear-spans a small plan; 2x8 is the house default. */
export function joistNominalFor(spanFt: number): string {
  return spanFt < SMALL_PLAN_WIDTH_FT ? '2x6' : (LUMBER.joistNominal.value as string);
}

/**
 * Frame a deck over the given bearings. Joists run along Z (front to rear) on the OC grid,
 * between rim joists at both ends — the same convention the frozen branch uses, so the two
 * floors read identically in the model even though they are generated by different code.
 */
export function generateFloorOnBearings(input: FloorSystemInput): Member[] {
  const { lengthFt: L, widthFt: W, deckTopY, stageFloor, stageDeck, prefix } = input;
  const emit = makeEmitter(prefix);

  const deckThickFt = input.deck === 'panel' ? (PANEL.subfloorThickIn.value as number) / IN_PER_FT
    : input.deck === 'plank' ? DRESSED[LUMBER.deckPlankNominal.value as string]!.w / IN_PER_FT
    : 0;

  const joistNominal = joistNominalFor(W);
  const joistD = DRESSED[joistNominal]!.d / IN_PER_FT;
  const t = DRESSED[joistNominal]!.w / IN_PER_FT;
  const joistTopY = deckTopY - deckThickFt;
  const joistY = joistTopY - joistD / 2;
  const oc = input.joistSpacingIn / IN_PER_FT;

  const joistCite = `${citeOf(LUMBER.joistNominal)}${W < SMALL_PLAN_WIDTH_FT ? ' — girderless clear span below 8 ft of width' : ''}`;

  // Layout grid along X: ends flush, interior on exact OC multiples.
  const centers: number[] = [t / 2];
  for (let s = oc; s < L - 1.5 * t; s += oc) centers.push(s);
  centers.push(L - t / 2);

  for (const x of centers) {
    emit('joist', joistNominal, {
      cutLengthFt: W - 2 * t,
      position: [x, joistY, W / 2],
      rotation: [0, -Math.PI / 2, 0],
      stage: stageFloor,
      nailing: '3-16d toenail each bearing (PH)',
      doctrineRef: joistCite,
    });
  }
  for (const z of [t / 2, W - t / 2]) {
    emit('rimJoist', joistNominal, {
      cutLengthFt: L,
      position: [L / 2, joistY, z],
      rotation: [0, 0, 0],
      stage: stageFloor,
      nailing: '3-16d each joist end (PH)',
      doctrineRef: citeOf(LUMBER.joistNominal),
    });
  }

  // Bridging: a row wherever an unsupported span reaches the doctrinal limit. With no interior
  // bearing (small plan) the whole width is one span.
  if (input.bridging !== false) {
    const interior = input.bearings.filter((b) => b.kind === 'girder' || b.kind === 'capBeam');
    const stations = [0, ...interior.map((b) => (b.from[1] + b.to[1]) / 2).sort((a, b) => a - b), W];
    const nominal = LUMBER.crossBridgingNominal.value as string;
    for (let i = 0; i < stations.length - 1; i++) {
      const span = stations[i + 1]! - stations[i]!;
      if (span < (LAYOUT.bridgingThresholdFt.value as number)) continue;
      const zMid = (stations[i]! + stations[i + 1]!) / 2;
      for (let k = 0; k < centers.length - 1; k++) {
        const gap = centers[k + 1]! - centers[k]! - t;
        if (gap < TOLERANCE.minBayFt) continue;
        // The rise that fits the BOARD between the joists, not just its centreline — the board's
        // own width is what used to push every piece out past the soffit and the deck. See
        // `bridgingRise.ts`.
        const rise = crossBridgingRise(gap, DRESSED[nominal]!.d / IN_PER_FT, joistD - TOLERANCE.bridgingInsetFt);
        if (rise <= 0) continue;
        const len = Math.hypot(gap, rise);
        const ang = Math.atan2(rise, gap);
        for (const s of [-1, 1] as const) {
          emit('bridging', nominal, {
            cutLengthFt: len,
            position: [(centers[k]! + centers[k + 1]!) / 2, joistY, zMid + s * TOLERANCE.bridgingSplayFt],
            rotation: [0, 0, s * ang],
            stage: stageFloor,
            nailing: '2-8d each end; bottom ends after the deck (PH)',
            doctrineRef: citeOf(LAYOUT.bridgingRowMaxFt),
          });
        }
      }
    }
  }

  // ── Deck
  if (input.deck === 'panel') {
    const sheetW = PANEL.lengthFt.value as number; // 8 ft along X
    const sheetH = PANEL.widthFt.value as number; // 4 ft along Z
    const rows = Math.ceil(W / sheetH);
    for (let r = 0; r < rows; r++) {
      const rowW = Math.min(sheetH, W - r * sheetH);
      if (rowW < TOLERANCE.minSliverFt) continue;
      const zC = r * sheetH + rowW / 2;
      const stagger = r % 2 === 1 ? sheetW / 2 : 0;
      let x = 0;
      if (stagger > 0) {
        emit('subfloor', `${PANEL.widthFt.value}x${PANEL.lengthFt.value} panel`, {
          cutLengthFt: Math.min(stagger, L),
          position: [Math.min(stagger, L) / 2, deckTopY - deckThickFt / 2, zC],
          rotation: [-Math.PI / 2, 0, 0],
          stage: stageDeck,
          actual: { w: PANEL.subfloorThickIn.value as number, d: rowW * IN_PER_FT },
          nailing: '8d @ 6" edges / 12" field (PH)',
          doctrineRef: citeOf(PANEL.subfloorThickIn),
        });
        x = Math.min(stagger, L);
      }
      for (; x < L - TOLERANCE.epsFt; x += sheetW) {
        const w = Math.min(sheetW, L - x);
        emit('subfloor', `${PANEL.widthFt.value}x${PANEL.lengthFt.value} panel`, {
          cutLengthFt: w,
          position: [x + w / 2, deckTopY - deckThickFt / 2, zC],
          rotation: [-Math.PI / 2, 0, 0],
          stage: stageDeck,
          actual: { w: PANEL.subfloorThickIn.value as number, d: rowW * IN_PER_FT },
          nailing: '8d @ 6" edges / 12" field (PH)',
          doctrineRef: citeOf(PANEL.subfloorThickIn),
        });
      }
    }
  } else if (input.deck === 'plank') {
    const nominal = LUMBER.deckPlankNominal.value as string;
    const plankW = DRESSED[nominal]!.d / IN_PER_FT;
    const count = Math.max(1, Math.round(W / plankW));
    const cell = W / count;
    for (let i = 0; i < count; i++) {
      emit('deckPlank', nominal, {
        cutLengthFt: L,
        position: [L / 2, deckTopY - deckThickFt / 2, (i + 0.5) * cell],
        rotation: [-Math.PI / 2, 0, 0],
        stage: stageDeck,
        nailing: '2-16d each joist (PH)',
        doctrineRef: citeOf(LUMBER.deckPlankNominal),
      });
    }
  }

  return emit.members;
}
